import { expect, test } from '@playwright/test'

test('@cross-browser search supports named input, result navigation and focus return', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('evo-atlas-language', 'en'))
  await page.goto('./#/catalog')
  const trigger = page.getByRole('button', { name: 'Search', exact: true })
  await trigger.focus()
  await page.keyboard.press('Control+k')
  const input = page.getByRole('textbox', { name: 'Search taxa, intervals, events, places…' })
  await expect(input).toBeFocused()
  await input.fill('Jurassic')
  const first = page.locator('[data-search-result]').first()
  await expect(first).toBeVisible()
  await input.press('ArrowDown')
  await expect(first).toBeFocused()
  await page.keyboard.press('ArrowUp')
  await expect(input).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await trigger.click()
  await expect(input).toBeFocused()
  await expect(first).toBeVisible()
  await input.press('Enter')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page).not.toHaveURL(/#\/catalog$/)
})
