import { expect, test } from '@playwright/test'

test('map ages and bilingual sources work without JavaScript', async ({ page }) => {
  const payloads: string[] = []
  page.on('request', (request) => { if (/\.(?:js|wasm|gz)(?:\?|$)|\/data\/releases\//.test(request.url())) payloads.push(request.url()) })
  await page.goto('./zh/')
  await page.getByRole('navigation', { name: '主导航' }).getByRole('link', { name: '地图', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('轻量古地理地图')
  await expect(page.locator('.map-ages a')).toHaveCount(13)
  await expect(page.locator('.map-viewport img')).toBeVisible()
  await expect(page.locator('.map-tools')).toBeHidden()
  await page.locator('.map-ages a[href$="/cambrian/"]').click()
  await expect(page.locator('.reading-map h2')).toContainText('512.825 Ma')
  await expect(page.locator('.map-ages [aria-current]')).toHaveAttribute('href', '/evo/zh/map/cambrian/')
  await expect(page.getByRole('link', { name: 'CC-BY-4.0', exact: true })).toBeVisible()
  await page.locator('.language').getByRole('link', { name: 'EN', exact: true }).click()
  await expect(page).toHaveURL(/\/evo\/map\/cambrian\/$/)
  await expect(page.locator('.reading-map h2')).toHaveText('Cambrian · 512.825 Ma')
  expect(payloads).toEqual([])
})

test('map zoom, keyboard pan and reset stay light and mobile-friendly', async ({ browser, baseURL }) => {
  const context = await browser.newContext({ baseURL, javaScriptEnabled: true, viewport: { width: 390, height: 844 } })
  const page = await context.newPage()
  const scripts: string[] = []
  page.on('request', (request) => { if (request.resourceType() === 'script') scripts.push(new URL(request.url()).pathname) })
  await page.goto('./zh/map/')
  await expect(page.locator('.map-viewport img')).toBeVisible()
  expect(await page.locator('.map-viewport img').evaluate((image: HTMLImageElement) => image.complete && image.naturalWidth > 0)).toBe(true)
  await page.getByRole('button', { name: '放大', exact: true }).click()
  await expect(page.locator('.map-tools output')).toHaveText('150%')
  await page.locator('.map-viewport').focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.locator('.map-viewport img')).toHaveCSS('transform', /matrix\(1.5, 0, 0, 1.5, -40, 0\)/)
  await page.locator('.map-viewport').scrollIntoViewIfNeeded()
  const bounds = await page.locator('.map-viewport').boundingBox()
  expect(bounds).not.toBeNull()
  await page.mouse.move(bounds!.x + bounds!.width / 2, bounds!.y + bounds!.height / 2)
  await page.mouse.down()
  await page.mouse.move(bounds!.x + bounds!.width / 2 + 20, bounds!.y + bounds!.height / 2)
  await page.mouse.up()
  await expect(page.locator('.map-viewport img')).toHaveCSS('transform', /matrix\(1.5, 0, 0, 1.5, -20, 0\)/)
  await page.getByRole('button', { name: '重置视图' }).click()
  await expect(page.locator('.map-tools output')).toHaveText('100%')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(scripts).toEqual(['/evo/map-controls.js'])
  await context.close()
})
