// @vitest-environment node
import { describe, expect, it } from 'vitest'
import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, readdirSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
const root=fileURLToPath(new URL('../',import.meta.url)); const archive=join(root,'data/sources/archives/checklistbank-1127-cestoda-2026-09-01.zip'); const script=join(root,'scripts/build-worms-cestoda-source.py'); const outDir=o=>join(o,'data/catalogue-of-life/releases/2026-08-20/resource-packs/other-animals')
describe('Cestoda archive projection',()=>{it('rebuilds isolated outputs and preserves canonical bytes',()=>{const canonical=join(root,'data/sources/worms-cestoda-archive-1127-import-ledger.json'); const cdir=outDir(root); const cb=Object.fromEntries(readdirSync(cdir).filter(f=>f.startsWith('worms-cestoda-')).map(f=>[f,readFileSync(join(cdir,f))])); const lb=readFileSync(canonical); const outs=[mkdtempSync(join(tmpdir(),'cestoda-one-')),mkdtempSync(join(tmpdir(),'cestoda-two-'))]; try { for(const out of outs) execFileSync('python',['-B',script,'--archive',archive,'--output-root',out],{cwd:root,stdio:'pipe'}); const files=o=>readdirSync(outDir(o)).sort(); expect(files(outs[0])).toEqual(files(outs[1])); for(const f of files(outs[0])) { expect(readFileSync(join(outDir(outs[0]),f))).toEqual(readFileSync(join(outDir(outs[1]),f))); expect(readFileSync(join(outDir(outs[0]),f))).toEqual(cb[f]) }; expect(readFileSync(join(outs[0],'data/sources/worms-cestoda-archive-1127-import-ledger.json'))).toEqual(readFileSync(join(outs[1],'data/sources/worms-cestoda-archive-1127-import-ledger.json'))); const d=JSON.parse(readFileSync(join(outDir(outs[0]),'worms-cestoda-sidecar.json'))); expect(d.source).toMatchObject({title:'World List of Cestoda',versionDoi:'10.48580/d3cw.v84',metadataSha256:expect.any(String)}); expect(d.counts).toMatchObject({total:3015,records:3054,accepted:3008,unmatched:7,upstreamOnly:39}); expect(d.deliveryProfiles['web-light'].records).toBe(0); expect(d.deliveryProfiles['native-full'].records).toBe(3054); expect(readFileSync(canonical)).toEqual(lb); for(const [f,b] of Object.entries(cb)) expect(readFileSync(join(cdir,f))).toEqual(b) } finally { for(const out of outs) rmSync(out,{recursive:true,force:true}) }},120000)})
