"""Build the pinned ChecklistBank 1033 Ichthyosporea projection offline."""
import argparse,csv,gzip,hashlib,json,tarfile
from io import StringIO
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; PACK=ROOT/'data/catalogue-of-life/releases/2026-08-20/resource-packs/protists-chromists'
DEFAULT=ROOT/'data/sources/archives/checklistbank-1033-trichomycetes-2017-10-27.tar.gz'; OUT=PACK/'trichomycetes-000.json.gz'; DESC=PACK/'trichomycetes-sidecar.json'; LEDGER=ROOT/'data/sources/trichomycetes-archive-import-ledger.json'
URL='https://api.checklistbank.org/dataset/1033/archive'; SHA='ad2f2a5e8b9feab455f73ac390be34908687f79fea4c858ade29e52a8acfc33e'; ARCHIVE_BYTES=38716
def digest(x): return hashlib.sha256(x).hexdigest()
def clean(x): return ' '.join((x or '').split())
def tsv(x): return list(csv.DictReader(StringIO(x.decode('utf-8-sig')),delimiter='\t'))
def main():
 p=argparse.ArgumentParser(); p.add_argument('--archive',default=str(DEFAULT)); archive=Path(p.parse_args().archive); raw=archive.read_bytes()
 if len(raw)!=ARCHIVE_BYTES or digest(raw)!=SHA: raise SystemExit('pinned archive bytes/hash mismatch')
 with tarfile.open(archive,'r:gz') as tf:
  members={n:tf.extractfile(n).read() for n in ('AcceptedSpecies.tsv','NameReferences.tsv','References.tsv','SourceDatabase.tsv')}
 src=tsv(members['AcceptedSpecies.tsv']); names=tsv(members['NameReferences.tsv']); refs=tsv(members['References.tsv']); byref={r['ReferenceID']:r for r in refs}; refs_by={}
 for i,n in enumerate(names,2):
  if n['ReferenceType']!='NomRef' or n['ReferenceID'] not in byref: raise SystemExit('invalid/missing NameReferences reference')
  refs_by.setdefault(n['ID'],[]).append({'referenceId':n['ReferenceID'],'referenceType':'NomRef','sourceRow':i,'reference':byref[n['ReferenceID']]})
 m=json.loads((PACK/'manifest.json').read_text(encoding='utf-8')); col=[]
 for f in m['files']:
  with gzip.open(ROOT/'data/catalogue-of-life/releases/2026-08-20/resource-packs'/f['path'],'rt',encoding='utf-8') as h: col += [json.loads(x) for x in h if x.strip()]
 targets=[x for x in col if x.get('rank')=='species' and x.get('status')=='accepted' and str(x.get('sourceDatasetId'))=='1033']; proto=[r for r in src if r['Kingdom']=='Protozoa']; ich=[r for r in proto if r['Class']=='Ichthyosporea']; fungi=[r for r in src if r['Kingdom']=='Fungi']; bykey={(clean(r['Genus']+' '+r['SpeciesEpithet']),clean(r['AuthorString'])):r for r in ich}; out=[]
 for c in targets:
  a=clean(c.get('authorship')); n=c['scientificName']; bare=n[:-len(a)-1] if a and n.endswith(' '+a) else n; r=bykey.get((clean(bare),a))
  if r is None: raise SystemExit('target not unique Ichthyosporea: '+c['id'])
  sid=r['AcceptedTaxonID']; sn=clean(r['Genus']+' '+r['SpeciesEpithet']); matched={'id':sid,'scientificName':sn,'authorship':r['AuthorString'],'status':r['Sp2000NameStatus'],'url':r['SpeciesURL']}
  out.append({'colId':c['id'],'colScientificName':c['scientificName'],'colAuthorship':a,'status':'accepted','matchedName':matched,'acceptedName':matched,'candidates':[],'mappingBasis':'Exact source name+authorship match; source fields preserved.','sourceRows':[{'member':'AcceptedSpecies.tsv','row':src.index(r)+2}],'sourceAcceptedTaxonId':sid,'sourceUrl':r['SpeciesURL'],'sourceClassification':{k:r[k] for k in ('Kingdom','Phylum','Class','Order')},'nameReferences':refs_by.get(sid,[])})
 out.sort(key=lambda x:x['colId']); payload=(json.dumps(out,ensure_ascii=False,separators=(',',':'))+'\n').encode(); OUT.parent.mkdir(parents=True,exist_ok=True)
 with OUT.open('wb') as f:
  with gzip.GzipFile(filename='',fileobj=f,mode='wb',mtime=0) as z:z.write(payload)
 ob=OUT.read_bytes(); mm={k:{'bytes':len(v),'sha256':digest(v)} for k,v in members.items()}; excluded=[r['AcceptedTaxonID'] for r in proto if r not in ich]
 d={'schemaVersion':1,'recordType':'release-pinned-authority-archive-crosswalk','id':'trichomycetes-archive-crosswalk','packageId':'protists-chromists','provider':'Trichomycetes – Fungi Associated with Arthropods via ChecklistBank','rowEncoding':'json','colIdField':'colId','totalCountField':'total','source':{'provider':'University of Kansas Trichomycetes database via Catalogue of Life ChecklistBank','license':'CC-BY-4.0','licenseUrl':'https://creativecommons.org/licenses/by/4.0/','archiveUrl':URL,'archiveBytes':ARCHIVE_BYTES,'archiveSha256':SHA,'archiveEncoding':'gzip-compressed tar (HTTP Content-Type application/zip)','version':'Oct 2017','versionDoi':'10.48580/d38n.v9','retrievedAt':'2026-09-04','members':mm},'scope':{'colSourceDatasetId':1033,'sourceKingdom':'Protozoa','sourcePhylum':'Choanozoa','sourceClass':'Ichthyosporea','eligibleColSpecies':len(targets),'projectedSpecies':len(out),'excludedSourceFungiRows':len(fungi),'excludedOtherProtozoaRows':len(excluded),'excludedOtherProtozoaIds':excluded,'matchingKey':'exact source scientific name + authorship'},'matching':{'normalization':'Strict UTF-8 quoted TSV; whitespace-only name+authorship comparison.','prohibited':'No fuzzy or inferred matching.'},'counts':{'total':len(out),'accepted':len(out),'redirect':0,'ambiguous':0,'unmatched':0,'withheld':0,'upstreamOnly':0,'records':len(out)},'files':[{'path':'protists-chromists/trichomycetes-000.json.gz','records':len(out),'bytes':len(ob),'sha256':digest(ob),'sourceBytes':len(payload),'sourceSha256':digest(payload),'minColId':out[0]['colId'],'maxColId':out[-1]['colId'],'encoding':'gzip','mediaType':'application/json','role':'col-partition'}],'upstreamOnlyFiles':[],'evidenceBoundary':{'en':'Frozen source provenance, not independent scientific corroboration, species-concept equivalence, biological dossier, fossil evidence or expert review.','zh':'冻结的来源追溯，不是独立科学佐证、物种概念等同、生物档案、化石证据或专家审查。'},'limitations':['Only the 96 COL strict accepted source-1033 Ichthyosporea rows are projected; excluded rows are not upstream-only.'],'descriptorSha256':'','totalCompressedBytes':len(ob),'totalSourceBytes':len(payload),'deliveryProfiles':{'web-light':{'payload':'summary-only','files':[],'records':0,'totalCompressedBytes':0,'totalSourceBytes':0},'native-full':{'payload':'complete','files':['protists-chromists/trichomycetes-000.json.gz'],'records':len(out),'totalCompressedBytes':len(ob),'totalSourceBytes':len(payload)}}}
 DESC.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); ledger={'schemaVersion':1,'importType':'COL26.8-to-ChecklistBank-1033-Ichthyosporea-source-archive','source':d['source'],'scopeAudit':{'method':'Exact name+authorship; source Kingdom Protozoa and Class Ichthyosporea','archiveAcceptedSpeciesRows':len(src),'archiveProtozoaRows':len(proto),'archiveIchthyosporeaRows':len(ich),'colEligibleSpecies':len(targets),'matchedUniqueSourceAcceptedTaxonIds':len({x['sourceAcceptedTaxonId'] for x in out}),'excludedFungiRows':len(fungi),'excludedOtherProtozoaRows':len(excluded),'excludedOtherProtozoaIds':excluded},'output':{'path':'data/catalogue-of-life/releases/2026-08-20/resource-packs/protists-chromists/trichomycetes-000.json.gz','bytes':len(ob),'sha256':digest(ob),'sourceBytes':len(payload),'sourceSha256':digest(payload)}}; LEDGER.write_text(json.dumps(ledger,ensure_ascii=False,indent=2)+'\n',encoding='utf-8'); print(json.dumps({'records':len(out),'outputBytes':len(ob)}))
if __name__=='__main__':main()
