import { createHash } from 'node:crypto'
import { gunzipSync } from 'node:zlib'
import { readFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { colExactMatchName, normalizeScientificName } from './itis-mammal-sidecar-lib.mjs'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const read = (path) => readFileSync(join(ROOT, ...path.split('/')))
const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex')

describe('checked-in ITIS Crustacea sidecar', () => {
  const ledger = JSON.parse(read('data/sources/itis-crustacea-authority-import-ledger.json').toString('utf8'))
  const descriptorPath = ledger.outputs.descriptor.path
  const descriptor = JSON.parse(read(descriptorPath).toString('utf8'))

  it('pins the exact COL and ITIS boundary without claiming mixed-package coverage', () => {
    expect(ledger.scopeAudit.colRootUsageId).toBe('KZX8B')
    expect(ledger.scopeAudit.colStrictAcceptedSpecies).toBe(80890)
    expect(ledger.scopeAudit.mixedPackageAcceptedSpecies).toBe(1049133)
    expect(ledger.scopeAudit.itisRoot).toMatchObject({ tsn: '83677', scientificName: 'Crustacea', rank: 'Subphylum', usage: 'valid' })
    expect(ledger.totals).toMatchObject({ total: 80890, itisCurrentSpecies: 32493, itisSpeciesSynonymLinks: 7762 })
    expect(ledger.deliveryContract.androidIosFull).toContain('byte-for-byte')
    expect(descriptor.scope).toContain('Crustacea usage KZX8B')
    expect(descriptor.scope).toContain('outside this sidecar')
  })

  it('covers deterministic, non-overlapping COL usage ranges', () => {
    const files = descriptor.colUsageIdLocator.files
    let previousLast = null
    let recordCount = 0
    for (const file of files) {
      const compressed = read(file.path)
      expect(compressed.length).toBe(file.bytes)
      expect(sha256(compressed)).toBe(file.sha256)
      const source = gunzipSync(compressed)
      expect(source.length).toBe(file.sourceBytes)
      expect(sha256(source)).toBe(file.sourceSha256)
      const records = source.toString('utf8').trimEnd().split('\n').map((line) => JSON.parse(line))
      expect(records.length).toBe(file.records)
      expect(records[0].colUsageId).toBe(file.firstColUsageId)
      expect(records.at(-1).colUsageId).toBe(file.lastColUsageId)
      if (previousLast) expect(previousLast < file.firstColUsageId).toBe(true)
      previousLast = file.lastColUsageId
      recordCount += records.length
      for (const record of records) {
        expect(record.exactMatchName).toBe(colExactMatchName({ scientificName: record.colScientificName, authorship: record.colAuthorship }))
        if (record.status === 'accepted') expect(normalizeScientificName(record.currentName.scientificName)).toBe(record.exactMatchName)
        if (record.status === 'synonym-current-name-redirect') expect(record.matchedSynonyms.length).toBeGreaterThan(0)
        if (record.status === 'ambiguous') expect(record.candidates.length).toBeGreaterThan(1)
      }
    }
    expect(recordCount).toBe(80890)
  })

  it('keeps ITIS-only rows outside COL ownership and pins generated bytes', () => {
    const upstream = descriptor.upstreamOnly.files[0]
    const upstreamBytes = read(upstream.path)
    expect(sha256(upstreamBytes)).toBe(upstream.sha256)
    const upstreamRecords = gunzipSync(upstreamBytes).toString('utf8').trimEnd().split('\n').map((line) => JSON.parse(line))
    expect(upstreamRecords.length).toBe(ledger.totals.itisUpstreamOnly)
    expect(upstreamRecords.every((record) => record.colUsageId === null && record.currentName?.tsn)).toBe(true)
    const canonical = read(ledger.canonical.path)
    expect(sha256(canonical)).toBe(ledger.canonical.sha256)
    const script = read(ledger.generatedBy.scriptPath)
    expect(sha256(script)).toBe(ledger.generatedBy.scriptSha256)
  })
})
